import './globals.css'
import { Inter } from 'next/font/google'
import { GlobalContextProvider } from '@/contexts/GlobalContext'
import { Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Hector Facundo Arana',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <GlobalContextProvider>
              <body className={poppins.className}>{children}</body>
        </GlobalContextProvider>
    </html>
  )
}
